CREATE TABLE DIAGNOSIS (
    ICD_10_CM VARCHAR(7) NOT NULL,
    Patient_ID INT NOT NULL,
    ServPro_SSN CHAR(9) NOT NULL,
    D_Name VARCHAR(30) NOT NULL,
    PRIMARY KEY (ICD_10_CM),
    FOREIGN KEY (Patient_ID)
        REFERENCES PATIENT (PID),
    FOREIGN KEY (ServPro_SSN)
        REFERENCES SERVICE_PROVIDER (SSN)
);
