CREATE TABLE EMERGENCY_CONTACT (
    Emer_ID INT NOT NULL,
    E_Name VARCHAR(25) NOT NULL,
    Address VARCHAR(50) NOT NULL,
    Phone CHAR(10) NOT NULL,
    Email VARCHAR(25),
    PRIMARY KEY (Emer_ID)
);
