CREATE TABLE LOGS (
    In_Time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Out_Time TIMESTAMP NOT NULL,
    SSN CHAR(9) NOT NULL,
    PID INT NOT NULL,
    PRIMARY KEY (SSN , PID),
    FOREIGN KEY (SSN)
        REFERENCES SERVICE_PROVIDER (SSN),
    FOREIGN KEY (PID)
        REFERENCES PATIENT (PID),
    CHECK (In_Time <= Out_Time)
);
