CREATE TABLE NOTES (
    ServPro_SSN CHAR(9) NOT NULL,
    Nurse_SSN CHAR(9) NOT NULL,
    PRIMARY KEY (ServPro_SSN , Nurse_SSN),
    FOREIGN KEY (ServPro_SSN)
        REFERENCES SERVICE_PROVIDER (SSN),
    FOREIGN KEY (Nurse_SSN)
        REFERENCES NURSE (SSN)
);
