CREATE TABLE TREATMENT (
    ICD_10_PCS VARCHAR(7) NOT NULL,
    Patient_ID INT NOT NULL,
    Serv_ID CHAR(9) NOT NULL,
    Cost INT,
    T_Name VARCHAR(30) NOT NULL,
    PRIMARY KEY (ICD_10_PCS , Patient_ID , Serv_ID),
    FOREIGN KEY (Patient_ID)
        REFERENCES PATIENT (PID),
    FOREIGN KEY (Serv_ID)
        REFERENCES SERVICE_PROVIDER (SSN)
);
